### ISSUE TITLE
getting odd syntax error

### ISSUE THREAD

**Issue by bweezy21** [honest-mule/Drive2CloudSync#4]
getting this weird syntax error eventhough syntax seems fine. (python 2.7)

![image](https://github.com/honest-mule/Drive2CloudSync/assets/8197439/168b1898-b1ad-4f72-80f1-e81573f56f0d)

getting this error with python 3.11

![image](https://github.com/honest-mule/Drive2CloudSync/assets/8197439/d0aa7a96-cd70-49f7-9a80-e94d3fe518f1)

**Comment by honest-mule** [comment]
It's not a python 2.x project so it won't run with the older python versions.

For the error with python 3.11, can you please try following a tutorial for running SQLite with python 3.10+ and see if that's working on your machine? (https://datagy.io/python-sqlite-tutorial/)

The error you're showing basically means that it's unable to create & connect with the SQLite database; as long as you've the latest python and you're making the right imports it should just do it. Because that's not the case at your end, you've to ensure python + SQLite is workable on your machine.

**Comment by bweezy21** [comment]
so following the tutorial you provided i am able to create the db orders.db. it looks like i'm failing on cache.py line 26 self.conn = sqlite3.connect(db_file) with error 'unable to open database file'. so for whatever reason this cannot be created - r".\cache\managed_list.db"

**Comment by bweezy21** [comment]
looks like i fixed it. there is not "cache" directory in the Drive2CloudSync directory. I had to create that directory first.

**Comment by honest-mule** [comment]
Weird that it didn't create a `cache` folder for you by default, maybe that's a bug in the script I will most likely fix it if that's the case.

Let me know if you face any other issues.
